### ISSUE TITLE
regex for "US currency" test case

### ISSUE THREAD

**Issue by cruxic** [snake5/sgregex#1]
I'm testing a few "real world" regex's from regexlib.com.

This "US currency" regex does not match "$1,234,567.89" but it should.
^\$([0-9]{1,3}(\,[0-9]{3})*|([0-9]+))(.[0-9]{2})?$

It works on these:

Matches
$0.84 | $123458

Non-Matches  
$12,3456.01 | 12345 | $1.234

**Comment by archo5** [comment]
Thanks for finding this example, it seems that there's a bug somewhere that I should fix.

**Comment by archo5** [comment]
Looks like it's fixed now: https://github.com/snake5/sgregex/commit/c334eab03f9a7dbf1b3e8f7b385fa577e48e5506
