### ISSUE TITLE
regex for "dutch phone numbers" test case

### ISSUE THREAD

**Issue by cruxic** [snake5/sgregex#2]
I'm testing a few "real world" regex's from regexlib.com.

This "dutch-style phone number" regex does not match "023-5256677" but it should.

(^+[0-9]{2}|^+[0-9]{2}(0)|^(+[0-9]{2})(0)|^00[0-9]{2}|^0)([0-9]{9}$|[0-9-\s]{10}$)

It works on these:

Matches  
+31235256677 | +31(0)235256677

Non-Matches  
+3123525667788999 | 3123525667788 | 232-2566778

**Comment by archo5** [comment]
This library currently does not support things like "\s" inside character classes. Also, "-" should be first (or right after "^") to be interpreted as a character. Rewriting that [0-9-\s] to [- 0-9] makes the regex match that number.

I intend to make some upgrades for character classes, this is just the way to make things work for now.

**Comment by cruxic** [comment]
Excellent, I didn't see that \s in there.  I didn't even know things like "\s" were allowed in brackets.  Seems shady.  As far as I'm concerned you can close this issue.

**Comment by archo5** [comment]
Finally found the time to rewrite most of the library to fix various issues, including this one.

https://github.com/snake5/sgregex/blob/master/sgregex_test.c#L744
